### ISSUE TITLE
Updated to 1.1.5.6: All Printers Offline?

### ISSUE THREAD

**Issue by bolsoncerrado** [NotExpectedYet/OctoFarm#90] opened 2020-08-17 07:26 UTC
Just upgraded new to 1.5.5.6 (ie rm -rf OctoFarm, git clone, npm install) and now all my printers are "offline" for OctoFarm...
no matter how many times I hit RESYNC...

Any clues?

Thanks!

**Comment by NotExpectedYet** [comment] 2020-08-17 07:27
Are you using octoprint 1.4.1+? 

You need to use the user api key or generate an application key for it.

**Comment by bolsoncerrado** [comment] 2020-08-17 07:32
Ah darn!

Any quick tutorial on that?

**Comment by bolsoncerrado** [comment] 2020-08-17 07:46
OK created user Octofarm on each printer, created API for user, assiged OPERATOR permisions and edited printers on Octofarm. Now Octofarm reports printers as Online, but API and WEBSOCKET still remain in RED.

Does octofarm require any specific permissions set on the printer? admin instead of operator?

**Comment by NotExpectedYet** [comment] 2020-08-17 07:47
You need to use Admin permissions for now yes. 

Those changes all came at once with the loss of the API when OctoPrint updated. I will have checks been put in place for future versions to work with any key over the coming weeks.

**Comment by bolsoncerrado** [comment] 2020-08-17 07:51
COol thanks!

**Comment by bolsoncerrado** [comment] 2020-08-17 07:55
OK definetly mondays must be the worst day to handle these kind of things!

Went ahead, added Admin usergroups to each octofarm user on my octoprint instances and now all printers show as SHUTDOWN on octofarm! WTF! ROTFL!!!

Sorry bud!! don't hate me!!

**Comment by NotExpectedYet** [comment] 2020-08-17 07:56
It's ok ahaha. This permissions thing couldn't have come at a worse time for me. 

Could you pass me the latest OctoFarm-State.log please? 

Doesn't seem as simple as I first thought ahaha

**Comment by bolsoncerrado** [comment] 2020-08-17 07:58
[OctoFarm-State.log](https://github.com/NotExpectedYet/OctoFarm/files/5082901/OctoFarm-State.log)

**Comment by bolsoncerrado** [comment] 2020-08-17 07:59
P.S. yes, i don't have all of them ON, just 3 or 4 for test purposes (printing actually, right now)

**Comment by NotExpectedYet** [comment] 2020-08-17 08:03
You've got the EHOST down error. 

Something on those OctoPrint boxes is still disconnecting the connection attempt to users. Maybe they need a restart to update the user permissions, I'm not sure as I'm new to OctoPrints permissions setup myself. 

Could you try completely wiping your printer on OctoFarm and re-adding it. It shouldn't matter that it's printing, and that's what another user did here to resolve the EHOST error. #89

**Comment by bolsoncerrado** [comment] 2020-08-17 08:14
Sure, lemme try that.

**Comment by bolsoncerrado** [comment] 2020-08-17 08:20
What a weirdo. Deleted 2. Readded both. One shows as awaiting, the other shows as half added :?? :?? I made sure both users octofarm are present and API are correctly copy/pasted.

<img width="1973" alt="Captura de pantalla 2020-08-17 a las 10 19 04" src="https://user-images.githubusercontent.com/10992914/90374096-3ef00680-e073-11ea-8ede-fd663fbd6f5b.png">

**Comment by NotExpectedYet** [comment] 2020-08-17 08:22
> What a weirdo. Deleted 2. Readded both. One shows as awaiting, the other shows as half added :?? :?? I made sure both users octofarm are present and API are correctly copy/pasted.
> 
> <img alt="Captura de pantalla 2020-08-17 a las 10 19 04" width="1973" src="https://user-images.githubusercontent.com/10992914/90374096-3ef00680-e073-11ea-8ede-fd663fbd6f5b.png">
> 
> Plus the second reads NO API WTF lol
> 
> Ps. Sent you my hangouts email just in case you wanna chat in realtime to fix this faster?

Sadly I can't I'm at work at the minute. 

I'm at a loss at the minute sadly as well. As far as I can tell it looks like it's still denying the connection. 

I'll run some more tests tonight starting with the old setup -> upgrading for you.

**Comment by bolsoncerrado** [comment] 2020-08-17 08:24
Is there a way to empty the printers db completely to start fresh? i mean not just deleting the rows manually thru the web GUI but resetting the db somehow to the "first time user" state...

**Comment by NotExpectedYet** [comment] 2020-08-17 08:29
> Is there a way to empty the printers db completely to start fresh? i mean not just deleting the rows manually thru the web GUI but resetting the db somehow to the "first time user" state...

Yeah for OctoFarm it's just a case of changing the URL in the database URI field of db.js. 

you'll have something like `https://localhost:27127/octofarm`
You can make a new database by `https://localhost:27127/octofarm2`

**Comment by bolsoncerrado** [comment] 2020-08-17 08:46
OK how do I stop Octofarm? npm stop did not work lol

**Comment by NotExpectedYet** [comment] 2020-08-17 08:47
`pm2 kill`

**Comment by bolsoncerrado** [comment] 2020-08-17 09:01
Well at least starting blank makes it partly coherent... Will await your input then:

<img width="1190" alt="Captura de pantalla 2020-08-17 a las 10 59 54" src="https://user-images.githubusercontent.com/10992914/90377916-fe938700-e078-11ea-9089-bd28c4794f35.png">

**Comment by NotExpectedYet** [comment] 2020-08-17 09:03
> Well at least starting blank makes it partly coherent... Will await your input then:
> 
> <img alt="Captura de pantalla 2020-08-17 a las 10 59 54" width="1190" src="https://user-images.githubusercontent.com/10992914/90377916-fe938700-e078-11ea-9089-bd28c4794f35.png">

Could you forward the latest state log again with the new setup? 

Sorry I can't advise more at the moment, I'll certainly get around to checking it out tonight.

**Comment by bolsoncerrado** [comment] 2020-08-17 09:03
[OctoFarm-State.log](https://github.com/NotExpectedYet/OctoFarm/files/5083241/OctoFarm-State.log)

**Comment by NotExpectedYet** [comment] 2020-08-17 09:13
From what the logs is telling me 1 of your printers is getting authenticated through the passive login, then the websocket is purposely failing it with EHOSTDOWN error. 

One of your other printers is just not getting past that at all and is been denied with the same error but at a different point. 

At the moment this is looking like OctoPrint is still denying the request (complete guess until I can confirm properly). 

I know some were printing, but do you have any to try rebooting and see if it's just that from when the permissions we're changed over? I'm wondering if OctoPrint needs something like that to enable them properly. 

It's seeming like the issue stems from a user been created with Observer privileges and then been set to Admin.

**Comment by bolsoncerrado** [comment] 2020-08-17 09:18
Sure, I'll turn on one of the non printing ones so I can reboot it upon creating the octofarm user and lyk.

**Comment by NotExpectedYet** [comment] 2020-08-17 09:19
Brilliant thank you very much!

**Comment by bolsoncerrado** [comment] 2020-08-17 09:24
So I did this:

1) Turned on offline printer+octoprint
2) Created octofarm + api user on octoprint
3) rebooted pi
4) once octoprint was back online, added printer to octofarm:

<img width="1206" alt="Captura de pantalla 2020-08-17 a las 11 23 54" src="https://user-images.githubusercontent.com/10992914/90380286-2afcd280-e07c-11ea-9d95-426816c28c92.png">

**Comment by bolsoncerrado** [comment] 2020-08-17 09:24
I can now add a 5th offline printer and then turn it on and add the api after adding it to octofarm but I have not much faith on that either lol

**Comment by NotExpectedYet** [comment] 2020-08-17 09:28
> I can now add a 5th offline printer and then turn it on and add the api after adding it to octofarm but I have not much faith on that either lol

Ones enough aha. Thanks for trying at least. 

I'll run off and do some testing in a dark corner tonight and see what madness I can produce. I've literally only tested this so far with the default admin user. Have you tried that? I totally understand if you don't want to give those permissions to octofarm btw, and like I said should work with any configuration. Due to having all the settings editing though I do require some lofty permissions at the moment as it will straight up fail the connection if one of those fails with how it was originally wrote. 

I will certainly get back to you as soon as I've tried re-producing your steps.

**Comment by bolsoncerrado** [comment] 2020-08-17 09:34
Some more weirdoo!!

https://www.dropbox.com/s/ybl3yfkt0w5pedk/ofwtf.mov?dl=0

**Comment by NotExpectedYet** [comment] 2020-08-17 09:36
> Some more weirdoo!!
> 
> https://www.dropbox.com/s/ybl3yfkt0w5pedk/ofwtf.mov?dl=0

That last one I will fix tonight :)

**Comment by Gerry-007** [comment] 2020-08-17 13:51
Hello there,

I do have the exact same problem.

I am running:

Version: 1.1.5.6.8
a vm with Ubuntu 18.04

Octoprint 1.4.2 and Application API
I am running four printer on the same octoprint (Raspberry Pi 3 B+)

looks like the API pass the info of the octoprint system (on line) but no info for the printer that result off-line
[OctoFarm-State16.log](https://github.com/NotExpectedYet/OctoFarm/files/5084608/OctoFarm-State16.log)

If I can help with my small knowledge...

**Comment by Gerry-007** [comment] 2020-08-17 14:03
Forget about the log I sent. 

That is the old installation
After going mad, this morning I reinstalled the lot, so the log I sent it refers to an old installation.

G

**Comment by Gerry-007** [comment] 2020-08-17 14:04
Here is the correct one.

G

[OctoFarm-State.log](https://github.com/NotExpectedYet/OctoFarm/files/5084700/OctoFarm-State.log)

**Comment by Gerry-007** [comment] 2020-08-17 14:05
Thank you for all your hard work!

**Comment by Gerry-007** [comment] 2020-08-17 14:43
You would expect that someone after 30 years working in IT, doing this for living, would not make mistake with typo an IP address.
The through is I am getting old!
I was trying to get the octopi on the same IP of the OctoFarm. Embarrassment!!!!

All working fine for me now.
Sending the first print on the prusa now.

I tested both API, the user and the Application and they both work fine.

Sorry to waist you time and again if you need any help......

Thank for the fab job.

G

**Comment by NotExpectedYet** [comment] 2020-08-17 14:50
> 
> 
> You would expect that someone after 30 years working in IT, doing this for living, would not make mistake with typo an IP address.
> The through is I am getting old!
> I was trying to get the octopi on the same IP of the OctoFarm. Embarrassment!!!!
> 
> All working fine for me now.
> Sending the first print on the prusa now.
> 
> I tested both API, the user and the Application and they both work fine.
> 
> Sorry to waist you time and again if you need any help......
> 
> Thank for the fab job.
> 
> G

No, thanks for getting back to me and saying it's fine! Those are the best kind of bugs ;) ahah

It's certainly not fresh installs as all mine auth fine. Also thanks for the kind words!

**Comment by bolsoncerrado** [comment] 2020-08-17 15:36
How do I test "the other" API?

I'm on MacOS fwiw... But I do plan to finally dedicate a miniOC to Octofarm, so it may run on Linux in the end... Or Windows, idk.

**Comment by NotExpectedYet** [comment] 2020-08-17 15:40
> 
> 
> How do I test "the other" API?
> 
> I'm on MacOS fwiw... But I do plan to finally dedicate a miniOC to Octofarm, so it may run on Linux in the end... Or Windows, idk.

The Application key as far as I'm aware uses the User permissions key. 

They are both in the user dropdown settings though if you want to try. 

How do you setup your users? as I gather they arn't setup as the default Admin account? I'll try and reproduce your setup shortly and see if I can get it working.

**Comment by Gerry-007** [comment] 2020-08-17 15:45
> How do I test "the other" API?

Octopi has three API possible

Global, User and Application
Please find the three snapshot of Octoprint below

If I am correct the Global key with the Octopi 1.4.2 is no longer supported.
![Screen Shot 2020-08-17 at 16 42 23](https://user-images.githubusercontent.com/69803315/90415442-00753e80-e0a9-11ea-87bf-5b42995fe6f0.png)
![Screen Shot 2020-08-17 at 16 42 40](https://user-images.githubusercontent.com/69803315/90415450-01a66b80-e0a9-11ea-96e7-4578ecfa5f1c.png)
![Screen Shot 2020-08-17 at 16 43 00](https://user-images.githubusercontent.com/69803315/90415454-02d79880-e0a9-11ea-8363-a6c466dbf6ed.png)

> 
> I'm on MacOS fwiw... But I do plan to finally dedicate a miniOC to Octofarm, so it may run on Linux in the end... Or Windows, idk.

**Comment by Gerry-007** [comment] 2020-08-17 15:46
I believe that the Application key is a Plugin

**Comment by NotExpectedYet** [comment] 2020-08-17 15:47
> 
> 
> > How do I test "the other" API?
> 
> Octopi has three API possible
> 
> Global, User and Application
> Please find the three snapshot of Octoprint below
> 
> If I am correct the Global key with the Octopi 1.4.2 is no longer supported.
> ![Screen Shot 2020-08-17 at 16 42 23](https://user-images.githubusercontent.com/69803315/90415442-00753e80-e0a9-11ea-87bf-5b42995fe6f0.png)
> ![Screen Shot 2020-08-17 at 16 42 40](https://user-images.githubusercontent.com/69803315/90415450-01a66b80-e0a9-11ea-96e7-4578ecfa5f1c.png)
> ![Screen Shot 2020-08-17 at 16 43 00](https://user-images.githubusercontent.com/69803315/90415454-02d79880-e0a9-11ea-8363-a6c466dbf6ed.png)
> 
> > I'm on MacOS fwiw... But I do plan to finally dedicate a miniOC to Octofarm, so it may run on Linux in the end... Or Windows, idk.

Yes only Application and User Keys will work, I think the Application key uses the Users permissions it was created under. Here it seems like the issue is something to do with the settings on the account maybe.

**Comment by bolsoncerrado** [comment] 2020-08-17 16:59
So there are only TWO APIs possible, the global one, now defunct for OctoFarm purposes, and the Access Control per User one, which is the one I moved to today, right?

Then I'm still out of the game. Hehe. 

How weird @Gerry-007 can get it fine. Wondering what's so different between OSs.

The ONLY thing I had to do is an nmp audit fix for 4 "problems" it was reporting upon installing this last version. 
Other than that, idk?

**Comment by Gerry-007** [comment] 2020-08-17 17:38
> So there are only TWO APIs possible, the global one, now defunct for OctoFarm purposes, and the Access Control per User one, which is the one I moved to today, right?
> 

![Screen Shot 2020-08-17 at 18 34 23](https://user-images.githubusercontent.com/69803315/90425841-4f76a000-e0b8-11ea-8c77-7d4f124bc2e0.png)
This is my access control for Admin
I am using the same Admin and password on the OctoFarm


> Then I'm still out of the game. Hehe.
> 
> How weird @Gerry-007 can get it fine. Wondering what's so different between OSs.

I don't think is a question of OS
> 
> The ONLY thing I had to do is an nmp audit fix for 4 "problems" it was reporting upon installing this last version.

I had that too, but if you have the webclient up I think the problem is only of communication to the Octopi.


You can do it!!


> Other than that, idk?

**Comment by NotExpectedYet** [comment] 2020-08-17 17:41
Do you by any chance have two user accounts on your OctoPrint instance? 

Just to clarify that npm audit fix is on some dev packages that I use. It's just warning you because they're in my package.json but they'll be fixed for next pull. 

OS doesn't matter though. It's confusing, I've only seen 1 other person with this issue and it was bugging me with what his was. My clean install works perfectly fine so there must be some configurational difference I can't think what else would cause this.

**Comment by bolsoncerrado** [comment] 2020-08-17 21:35
> > So there are only TWO APIs possible, the global one, now defunct for OctoFarm purposes, and the Access Control per User one, which is the one I moved to today, right?
> 
> ![Screen Shot 2020-08-17 at 18 34 23](https://user-images.githubusercontent.com/69803315/90425841-4f76a000-e0b8-11ea-8c77-7d4f124bc2e0.png)
> This is my access control for Admin
> I am using the same Admin and password on the OctoFarm
> 
> > Then I'm still out of the game. Hehe.
> > How weird @Gerry-007 can get it fine. Wondering what's so different between OSs.
> 
> I don't think is a question of OS
> 
> > The ONLY thing I had to do is an nmp audit fix for 4 "problems" it was reporting upon installing this last version.
> 
> I had that too, but if you have the webclient up I think the problem is only of communication to the Octopi.
> 
> You can do it!!
> 
> > Other than that, idk?

Ah but then you're not using latest octoprint right???

**Comment by bolsoncerrado** [comment] 2020-08-17 21:37
> Do you by any chance have two user accounts on your OctoPrint instance?
> 
> Just to clarify that npm audit fix is on some dev packages that I use. It's just warning you because they're in my package.json but they'll be fixed for next pull.
> 
> OS doesn't matter though. It's confusing, I've only seen 1 other person with this issue and it was bugging me with what his was. My clean install works perfectly fine so there must be some configurational difference I can't think what else would cause this.

Well as of today, octoprint admin is user 1 and Octofarm admin is user 2 on octoprint, yes. 

As on audit fix, do you mean it does not matter I ran it or it's best I shouldn't have run it?

**Comment by Gerry-007** [comment] 2020-08-17 21:49
> > > So there are only TWO APIs possible, the global one, now defunct for OctoFarm purposes, and the Access Control per User one, which is the one I moved to today, right?
> > 
> > 
> > ![Screen Shot 2020-08-17 at 18 34 23](https://user-images.githubusercontent.com/69803315/90425841-4f76a000-e0b8-11ea-8c77-7d4f124bc2e0.png)
> > This is my access control for Admin
> > I am using the same Admin and password on the OctoFarm
> > > Then I'm still out of the game. Hehe.
> > > How weird @Gerry-007 can get it fine. Wondering what's so different between OSs.
> > 
> > 
> > I don't think is a question of OS
> > > The ONLY thing I had to do is an nmp audit fix for 4 "problems" it was reporting upon installing this last version.
> > 
> > 
> > I had that too, but if you have the webclient up I think the problem is only of communication to the Octopi.
> > You can do it!!
> > > Other than that, idk?
> 
> Ah but then you're not using latest octoprint right???

I do.

Version 1.4.2

G

**Comment by bolsoncerrado** [comment] 2020-08-18 08:19
Doh!

I was using an additional user for octofarm, never thought using one different than the main admin would make a difference. Lemme try that.

**Comment by bolsoncerrado** [comment] 2020-08-18 08:22
RIGHT ON!

Using Admin's API makes it work again!!

**Comment by NotExpectedYet** [comment] 2020-08-18 08:28
> RIGHT ON!
> 
> Using Admin's API makes it work again!!

I know why this is as well. OctoFarm is in a position where I would rather make adding a printer as streamlined as possible... so, not asking for user credentials and that, or making you accept the auth request on the web ui... for someone with 60+ printers this is just annoying. This worked perfectly fine to begin with until the Global API key lock out. Now I gather there was some confusion between the key OctoFarm was using and the User it was attempting to login with! 

I will try and make sure this is more streamlined in the future, but honestly thank you for sticking through all this and testing it out. I now can at the very least make recommendations to other users who may face this issue. 

I will close this for now as the original issue has been resolved, and I'll make a not to have a look at a more graceful way of grabbing the specific user without confusing it between two that exist.

**Comment by bolsoncerrado** [comment] 2020-08-18 08:31
Thank you for this piece of software man!!

**Comment by NotExpectedYet** [comment] 2020-08-18 08:36
> Thank you for this piece of software man!!

You are most welcome! Glad its finally working properly :)

**Closed by NotExpectedYet** 2020-08-18 08:36 UTC
Labels: bug
