### ISSUE TITLE
1.1.4 - Unable to look at printer preferences. 

### ISSUE THREAD

**Issue by nkatsoulis** [NotExpectedYet/OctoFarm#17] opened 2020-03-31 07:04 UTC
Printer is on pi version 1.3.12

![image](https://user-images.githubusercontent.com/50277560/77996227-db974f00-72f2-11ea-9e97-9aa56b4e521d.png)

I can't seem to get any details in the control or other screens.

![image](https://user-images.githubusercontent.com/50277560/77996278-f36ed300-72f2-11ea-8bc4-1ade827e7e4c.png)

I have used the latest with the following compose file below.

version: "2"
services:
  octofarm:
    container_name: octofarm
    image: octofarm/octofarm
    restart: always
    ports:
      - 4000:4000
    environment:
      - MONGO=mongodb://octofarm_mongo/octofarm
    volumes:
      - /volume1/homes/admin/data/octofarm/config:/app/serverConfig
      - /volume1/homes/admin/data/octofarm/logs:/app/logs

  octofarm_mongo:
    container_name: octofarm_mongo
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - /volume1/homes/admin/data/bitnami:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2

**Comment by NotExpectedYet** [comment] 2020-03-31 07:18
I believe this issue is related to the profile issue I'm seeing with some users. 

Issue #15 

I can't reproduce personally and I don't know what's causing the issue yet. 

Will report back once I've had to test further.

**Comment by NotExpectedYet** [comment] 2020-03-31 07:19
Closing to track further on #15

**Closed by NotExpectedYet** 2020-03-31 07:19 UTC
Labels: bug
