### ISSUE TITLE
[BUG]: Cannot read property 'free' of undefined (fileManagerRunner.js)

### ISSUE THREAD

**Issue by bretterer** [NotExpectedYet/OctoFarm#108] opened 2020-09-07 22:25 UTC
One one of my printers, I can not do anything with the file manager.  I get the message

```
fileManagerRunner.js:256 Uncaught (in promise) TypeError: Cannot read property 'free' of undefined
    at Function.updatePrinterList (fileManagerRunner.js:256)
```

Only way I can make file manager work for my printer again is to fully remove the printer, and then re-add it. it then works fine for a little while.

I have 4 Ender 3 Pro's linked up to the system.  I am using the users application keys

<img width="1920" alt="Screen Shot 2020-09-07 at 6 23 45 PM" src="https://user-images.githubusercontent.com/1906920/92418765-4ae15c80-f137-11ea-968d-11a79c1bdcfa.png">
<img width="1912" alt="Screen Shot 2020-09-07 at 6 23 13 PM" src="https://user-images.githubusercontent.com/1906920/92418771-52086a80-f137-11ea-95ed-2580e715f1bb.png">

I'm not sure which logs will be helpful here, so please let me know and I can add them to the issue

**Comment by NotExpectedYet** [comment] 2020-09-08 02:23
OctoFarm state log please, oh and OctoFarm and OctoPrint versions. 

It's indicating that it's either not finished scanning your files/failed at some point sorry the UI doesn't react properly to the eventuality there seems to be an edge case getting through. 

If you Re-Sync the files of that specific printer for me before sending the logs it should be easy to spot.

**Comment by bretterer** [comment] 2020-09-08 14:52
OctoFarm: 1.1.5.6
OctoPrint: 1.4.2 
Python: 2.7.16 
OctoPi: 0.17.0

State Log:
[OctoFarm-State.log](https://github.com/NotExpectedYet/OctoFarm/files/5189027/OctoFarm-State.log)

Printer in question is ip `10.12.13.142`

Ran re-sync, but no UI update happened to show that re-sync was working or triggered at all

**Comment by NotExpectedYet** [comment] 2020-09-08 15:03
Thanks for that 

Checking through the logs it seems the client in question lost connection and become unreachable:
`Mon, 07 Sep 2020 21:27:08 GMT | ERROR | OctoFarm-State.log | Error: connect EHOSTUNREACH`
When it came back online it looks like OctoPrint wasn't allowing the connection back in:
`Mon, 07 Sep 2020 21:38:36 GMT | ERROR | OctoFarm-State.log | Error: read ECONNRESET` which could just be OctoPrint booting back up. 

I believe this eventually resolved itself and octofarm never re-scanned the files due to them already existing in the database. 

If you'd like to resolve this, you should be able to delete the printer and re-add it again with no adverse effects. History will all still be linked and that as it uses your ip/printer name. 

This is certainly a bug on OctoFarms side. I'm hoping to push the next release this weekend if not Friday so I'll make sure this doesn't happen again in the future.

**Comment by bretterer** [comment] 2020-09-09 13:28
Would you like me to test your `attempted fix`  on my end, or were you able to re-produce it?

Thank you for the quick turn around on this!

**Comment by NotExpectedYet** [comment] 2020-09-09 13:51
If your happy to run the latest development build then please do :) 

I tried to reproduce by deleting the storage key from the database so i believe it should solve the issue. I just havent had chance to investigae how the situation can possibly arrise as those values should be pulled when files are synced. Your system had files but was complaining the storage didnt exist, but i also tweaked the triggers for functions that run the information cleaners for the client with the last push so it shouldnt happen again. 

Thanks for been so quick on this i hadnt gotten around to asking ahaha.

**Comment by NotExpectedYet** [comment] 2020-09-09 13:53
Your most welcome as well!

**Comment by NotExpectedYet** [comment] 2020-09-20 13:40
This should be resolved now, closing please let me know if it's not the case

**Closed by NotExpectedYet** 2020-09-20 13:40 UTC
Labels: bug
