### ISSUE TITLE
Printers connected but not showing info (Related to issue #85)

### ISSUE THREAD

**Issue by byurick** [NotExpectedYet/OctoFarm#88] opened 2020-08-08 18:59 UTC
Was using a previous version of octofarm when I started having this issue so I upgraded it, no change. Then I did a fresh install and still having the same issues. Both printers are on octoprint 1.4.2 I can see the cameras and they say they're both online and connected but no filename/temperatures or the "current operations" tabs shows any info.

**Comment by NotExpectedYet** [comment] 2020-08-08 19:07
This is a duplicate of #85 as I haven't updated OctoFarm to work with 1.4.1+

**Comment by byurick** [comment] 2020-08-08 19:10
Thanks, I did see #85  but wasn't sure if it was the same.

**Comment by NotExpectedYet** [comment] 2020-08-08 19:15
No worries, I should have it updated tomorrow.

**Comment by bolsoncerrado** [comment] 2020-08-10 10:24
Came here with similar issues. However you reffer to it as #85 having socket issues, however I'm running both 1.41 and 1.42 in some printers but my webocket icons are all green :?

<img width="1320" alt="Captura de pantalla 2020-08-10 a las 12 22 38" src="https://user-images.githubusercontent.com/10992914/89773550-6f302600-db04-11ea-8f75-8a55eb7d0528.png">

**Comment by NotExpectedYet** [comment] 2020-08-10 17:48
> 
> 
> Came here with similar issues. However you reffer to it as #85 having socket issues, however I'm running both 1.41 and 1.42 in some printers but my webocket icons are all green :?
> 
> <img alt="Captura de pantalla 2020-08-10 a las 12 22 38" width="1320" src="https://user-images.githubusercontent.com/10992914/89773550-6f302600-db04-11ea-8f75-8a55eb7d0528.png">

This should be fixed on the latest RC, 

Would you mind trying it out at all? 

OctoFarm to save the users time makes a guess at the user you use. Going forward for 1.4.2 you will have to use either the user key or create an application key specifically for OctoFarm. My only other alternative was triggering the app registration plugin which would require you to open the octoprint web interface for each. I think that is why people are seeing different results though, anyone like me using the global key that will no longer work after upgrading octoprint to 1.4.2.

**Comment by bolsoncerrado** [comment] 2020-08-10 22:19
Yes, do I just git clone the latest Rc and that's all or do I need to enable the dev too?

My only other pending task is how to damn launch it upon boot up on macos, i cant figure it out 👍

**Comment by NotExpectedYet** [comment] 2020-08-11 14:35
> 
> 
> Yes, do I just git clone the latest Rc and that's all or do I need to enable the dev too?
> 
> I'm using the global key, not a specific one btw.
> 
> My only other pending task is how to damn launch it upon boot up on macos, i cant figure it out 👍

Yes that's it :) I'd probably setup a seperate instance but that's totally up to you. I've squashed a lot of bugs I just want to make sure no more exist before releasing properly. 

Have you checked the wiki? the latest version uses pm2 and can be made to run on startup for all the major OS'

**Comment by byurick** [comment] 2020-08-11 23:13
So far so good with the latest RC, seems to have cleared up all the connection issues I was seeing.

**Comment by NotExpectedYet** [comment] 2020-08-12 14:54
> 
> 
> So far so good with the latest RC, seems to have cleared up all the connection issues I was seeing.

Epic thanks for the report!

**Comment by Crowlord** [comment] 2020-08-12 16:36
Latset dev version loves my Kossel and works perfectly. 

All three prusas it hates. It won't even see them as online if i have a key entered (either the base api which shouldn't work anyway and the app key which i generated via user)

All on oprint 1.4.2

**Comment by NotExpectedYet** [comment] 2020-08-12 18:00
@Crowlord no that issue again. 

That's a crap regression and can only think it's the file scanning changes...

That's annoying. Could you open another ticket and put it down to specifically when a Prusa is attached and grab me some logs if you get chance? Also a decent description of what the UI is doing if anything.

**Comment by Crowlord** [comment] 2020-08-12 18:05
I will bundle you up some logs etc

**Comment by NotExpectedYet** [comment] 2020-08-12 18:06
@Crowlord legend thank you

**Comment by NotExpectedYet** [comment] 2020-08-16 14:49
Master updated closing this issue, should be resolved.

**Closed** 2020-08-16 14:48 UTC
Labels: bug, duplicate
