### ISSUE TITLE
OctoFarm resets feed rates

### ISSUE THREAD

**Issue by paukstelis** [NotExpectedYet/OctoFarm#28] opened 2020-04-10 15:17 UTC
I've noticed that OctoFarm resets feed rates (and perhaps flow rates?) after each print. Is there a way to alter this behaviour?

**Comment by NotExpectedYet** [comment] 2020-04-10 15:30
It doesn't reset them, it remembers your previously set feed/flow rate and re-applies that. 

Currently no but if you would like that feature please add it to my feathub page.

**Comment by paukstelis** [comment] 2020-04-10 15:38
That assumes the feed/flow changes were made through OctoFarm and not on the printer directly. I think most of the time those changes would be made while examining the print. I'll put in a request.

**Comment by NotExpectedYet** [comment] 2020-04-10 15:42
It does, but if your making the feed/flow rate changes there why not start the print from there?

**Comment by NotExpectedYet** [comment] 2020-04-10 15:49
Gonna close this ticket anyway as it's not a bug. 

Feel free to give me some use cases in your feat-hub :) would rather understand your process to try and get a better fit.

**Closed by NotExpectedYet** 2020-04-10 15:49 UTC
